#!/bin/sh

# Not needed for every project, but better than specifying for every of each

echo "deb http://de.archive.ubuntu.com/ubuntu/ precise universe" >> /etc/apt/sources.list
echo "deb http://de.archive.ubuntu.com/ubuntu/ precise-updates universe" >> /etc/apt/sources.list
echo "deb http://de.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse" >> /etc/apt/sources.list
apt-get update
apt-get install -y git lcov wget sudo check automake build-essential libtool pkg-config libgtest-dev google-mock dbus-test-runner xserver-xorg-dev xserver-xorg-video-dummy

cd /usr/bin
wget https://software.sandia.gov/trac/fast/export/2727/gcovr/trunk/scripts/gcovr
chmod +x gcovr

cd /tmp
git clone git://people.freedesktop.org/~cndougla/xorg-gtest
cd xorg-gtest
./autogen.sh
./configure --prefix=/usr
make && make install
