#!/bin/bash -e

if [ -x /usr/bin/bustle-pcap ]; then
	exec /usr/bin/bustle-pcap $@ 
fi

if [ -x /usr/bin/bustle-dbus-monitor ]; then
	exec /usr/bin/bustle-dbus-monitor $@
fi

echo "Unable to find a suitable Bustle capture tool"
exit 1

