#!/bin/sh

if [ -z "$BUILD_DIR" ]; then
    BUILD_DIR="`find /tmp/buildd -maxdepth 2 -mindepth 2 -name debian`/.."
fi

# Jump to build directory
cd "$BUILD_DIR"

if [ -f CMakeLists.txt ]; then
    cd obj-`dpkg-architecture -qDEB_BUILD_GNU_TYPE`
fi
# for gtk2/gtk3 specific build, go to the builddir
# FIXME: any other way to find a better builddir?
if [ -d build/gtk3 ]; then
    cd build/gtk3
fi

# Export results of unit testing in xml format
# for reporting purposes in jenkins
export GTEST_OUTPUT=xml

# Execute the unit test suite
make check

# Remember the exit status of the unit tests.
result=$?

# Generate coverage results
make generate-coverage-html
make generate-coverage-gcovr

# translate gtester results to be JUnit-compatible
for i in `find tests -name "*.xml"`; do j=`echo $i | sec 's/\.xml/~junit.xml/g'`; xsltproc -o $j ~/gtester.xsl "$i"; done

# Check for results dir
if [ -z "$RESULT_DIR" ]; then
    RESULT_DIR=`cat /tmp/buildd/ReportDir`
fi
mkdir -p "$RESULT_DIR/tests"

# Save the test & coverage results
cp -v coverage.xml "$RESULT_DIR"
cp -vR coveragereport "$RESULT_DIR"
find tests -name "*.xml" | xargs cp -vt "$RESULT_DIR/tests"

exit $result
