#!/bin/sh

# Not needed for every project, but better than specifying for every of each

echo "deb http://archive.ubuntu.com/ubuntu/ precise universe" >> /etc/apt/sources.list
echo "deb http://archive.ubuntu.com/ubuntu/ precise-updates universe" >> /etc/apt/sources.list
echo "deb http://archive.ubuntu.com/ubuntu/ precise-backports main restricted universe" >> /etc/apt/sources.list
apt-get update
apt-get install -y devscripts cdbs lcov wget sudo check automake build-essential libtool pkg-config equivs

cd /usr/bin
wget --no-check-certificate --timeout=10 --tries=3 http://ubuntuone.com/3XSIpokhRr4cjbuoYsaz4A -O gcovr
chmod +x gcovr

#cd /usr/bin
#wget --no-check-certificate --timeout=10 --tries=3 http://ubuntuone.com/3XSIpokhRr4cjbuoYsaz4A -O gcovr
#chmod +x gcovr

#cd /tmp
#wget --no-check-certificate --timeout=10 --tries=3 http://ubuntuone.com/7ROPr1GHatOCquGUwk6aC6 -O xorg-gtest.tar.bz2
#tar -xjf xorg-gtest.tar.bz2

#if [ -e xorg-gtest ]; then
#  cd xorg-gtest
#  ./autogen.sh
#  ./configure --prefix=/usr
#  make && make install
#fi
